### ISSUE TITLE
Can't import the named export 'randomBytes' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by joshje** [lukeed/csprng#2]
Hey folks, we’re getting an error when building for umd  with Webpack since adding an npm module that relies on this one:
```bash
    ERROR in ./node_modules/@lukeed/csprng/node/index.mjs 4:8-19
    Can't import the named export 'randomBytes' from non EcmaScript module (only default export is available)
     @ ./node_modules/@lukeed/uuid/secure/index.js
     @ ./node_modules/@itly/plugin-iteratively/dist/esm/index.js
     @ ./src/lib/analytics/itly/index.ts
     @ ./src/lib/analytics/index.js
```

Here’s the relevant part of our webpack config for the output:
```javascript
{
  target: 'node',
  output: {
    path: path.resolve(__dirname, '../dist/server'),
    filename: 'index.js',
    library: 'SnykFrontendComponents',
    libraryTarget: 'umd',
  }
}
```
Any advice on how we can restore our build whilst using this module?

**Comment by lukeed** [comment]
Hi there,

This is an issue on webpack's side -- it's not applying the same exports condition resolution to dependencies' dependencies. AKA, you're building `@lukeed/uuid` for the browser, which means that its `exports.browser` is traversed and the same should be true for `@lukeed/csprng`, which it depends on.

There's also no default import or export anywhere in these two modules. It's just a bad juggling from webpack.

To get around this, you can add an explicit alias to the file you want here: https://webpack.js.org/configuration/resolve/#resolvealias

```js
{
  alias: {
    '@lukeed/csprng': require.resolve('@lukeed/csprng/browser/index.mjs')
  }
}
```

Hope that helps!

**Comment by joshje** [comment]
Thanks @lukeed, that seems to have done the trick!
